### ISSUE TITLE
JS version infinite loop if reverse=true

### ISSUE THREAD

**Issue by postspectacular** [cubicdaiya/onp#4]
Since the `offset` should always be based on the length of the smaller array, the JS impl currently goes into an infinite loop due to not setting the offset correctly when swapping arrays.

Fix:

Add `offset = m + 1` at [line 37](https://github.com/cubicdaiya/onp/blob/master/javascript/onp.js#L37)

**Comment by cubicdaiya** [comment]
Hi @postspectacular,

Thank you for the report. I fixed in 497b1de7bd06e33f16a61e7369ae4fe7d42c90c2.
